"""Initial schema with denormalized tables

Revision ID: 6e191e0ff319
Revises: 
Create Date: 2025-11-07 20:15:14.915554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e191e0ff319'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Original file name'),
    sa.Column('file_path', sa.Text(), nullable=False, comment='MinIO storage path (e.g., documents/{uuid}/original.pdf)'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash for deduplication'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False, comment='File size in bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type of the file'),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='Document type: ciso_report, sec_filing, unknown'),
    sa.Column('doc_category', sa.String(length=50), nullable=True, comment='Document category: Form_8K, Incident_Report, etc.'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='Full extracted text from the document'),
    sa.Column('extraction_status', sa.String(length=20), nullable=False, comment='Extraction status: pending, processing, completed, failed'),
    sa.Column('extraction_error', sa.Text(), nullable=True, comment='Error message if extraction failed'),
    sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        Extraction metadata in JSON format. Example:\n        {\n            "num_pages": 12,\n            "tables_found": 3,\n            "extracted_at": "2025-11-07T15:30:00Z",\n            "landing_ai_job_id": "abc123",\n            "processing_time_ms": 3420,\n            "text_length": 45230,\n            "language": "en",\n            "confidence_score": 0.98\n        }\n        '),
    sa.Column('gemini_corpus_id', sa.String(length=100), nullable=True, comment='Google Gemini corpus ID if indexed'),
    sa.Column('gemini_document_id', sa.String(length=100), nullable=True, comment='Google Gemini document ID if indexed'),
    sa.Column('uploaded_by_email', sa.String(length=255), nullable=True, comment='Email of the user who uploaded the document'),
    sa.Column('uploaded_by_name', sa.String(length=255), nullable=True, comment='Name of the user who uploaded the document'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_category_status', 'documents', ['doc_category', 'extraction_status'], unique=False)
    op.create_index('idx_documents_metadata_gin', 'documents', ['extraction_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_type_status', 'documents', ['doc_type', 'extraction_status'], unique=False)
    op.create_index('idx_documents_uploaded_by', 'documents', ['uploaded_by_email', 'created_at'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_doc_category'), 'documents', ['doc_category'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_extraction_status'), 'documents', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_index(op.f('ix_documents_file_name'), 'documents', ['file_name'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_updated_at'), 'documents', ['updated_at'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_email'), 'documents', ['uploaded_by_email'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('framework', sa.String(length=50), nullable=False, comment='Compliance framework used for scanning'),
    sa.Column('scan_type', sa.String(length=20), nullable=False, comment='Type of scan: initial, incremental, rescan, targeted'),
    sa.Column('document_ids', sa.ARRAY(sa.UUID()), nullable=False, comment='Array of document IDs to scan'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Current status of the scan job'),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When the scan started processing'),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When the scan completed'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Total duration of scan in seconds'),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        Scan results summary. Example:\n        {\n            "violations_found": 3,\n            "documents_processed": 12,\n            "documents_failed": 0,\n            "critical_count": 1,\n            "high_count": 2,\n            "medium_count": 0,\n            "low_count": 0,\n            "violation_ids": ["uuid1", "uuid2", "uuid3"],\n            "failed_document_ids": [],\n            "processing_stats": {\n                "total_tokens_used": 45000,\n                "total_cost_usd": 0.576,\n                "avg_processing_time_ms": 3200\n            },\n            "top_violations": [\n                {\n                    "type": "material_omission",\n                    "count": 2\n                }\n            ]\n        }\n        '),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        Optional scan configuration. Example:\n        {\n            "severity_threshold": "medium",\n            "skip_categories": ["Form_10Q"],\n            "focus_rules": ["SEC Reg S-K Item 1C"],\n            "confidence_threshold": 0.8,\n            "max_violations_per_document": 10\n        }\n        '),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if scan failed'),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='\n        Detailed error information. Example:\n        {\n            "error_type": "API_ERROR",\n            "error_code": "BEDROCK_THROTTLED",\n            "stack_trace": "...",\n            "failed_at_document": "uuid",\n            "retry_count": 3\n        }\n        '),
    sa.Column('triggered_by_email', sa.String(length=255), nullable=True, comment='Email of user who triggered the scan'),
    sa.Column('triggered_by_name', sa.String(length=255), nullable=True, comment='Name of user who triggered the scan'),
    sa.Column('trigger_source', sa.String(length=50), nullable=True, comment='How scan was triggered: manual, scheduled, webhook, api'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_jobs_created_at'), 'scan_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_jobs_framework'), 'scan_jobs', ['framework'], unique=False)
    op.create_index(op.f('ix_scan_jobs_id'), 'scan_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scan_jobs_triggered_by_email'), 'scan_jobs', ['triggered_by_email'], unique=False)
    op.create_index(op.f('ix_scan_jobs_updated_at'), 'scan_jobs', ['updated_at'], unique=False)
    op.create_table('violations',
    sa.Column('source_document_id', sa.UUID(), nullable=False, comment='ID of the source document (e.g., CISO report)'),
    sa.Column('source_document_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        Denormalized source document data. Example:\n        {\n            "id": "uuid",\n            "file_name": "CISO_Report_Oct2024.pdf",\n            "doc_type": "ciso_report",\n            "file_size_bytes": 2457600,\n            "created_at": "2025-11-07T14:32:00Z",\n            "uploaded_by": "security@company.com"\n        }\n        '),
    sa.Column('target_document_id', sa.UUID(), nullable=False, comment='ID of the target document (e.g., SEC filing)'),
    sa.Column('target_document_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        Denormalized target document data. Example:\n        {\n            "id": "uuid",\n            "file_name": "Form_8K_Draft.docx",\n            "doc_type": "sec_filing",\n            "doc_category": "Form_8K",\n            "created_at": "2025-11-07T14:45:00Z",\n            "uploaded_by": "legal@company.com"\n        }\n        '),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='Compliance framework'),
    sa.Column('rule_citation', sa.Text(), nullable=False, comment="Specific rule or regulation citation (e.g., 'SEC Regulation S-K Item 1C')"),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severity level: critical, high, medium, low'),
    sa.Column('violation_type', sa.String(length=100), nullable=False, comment='Type of violation: material_omission, misleading_statement, etc.'),
    sa.Column('finding_summary', sa.Text(), nullable=False, comment='Brief summary of the violation finding'),
    sa.Column('explanation', sa.Text(), nullable=False, comment='Detailed explanation of why this is a violation'),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        Evidence supporting the violation. Example:\n        {\n            "source_quote": "Ransomware attack confirmed. 47,000 records exfiltrated...",\n            "source_page": 3,\n            "source_section": "Impact Assessment",\n            "source_context": "Full paragraph for context...",\n            "target_quote": "We may be subject to hypothetical cyber risks...",\n            "target_page": 1,\n            "target_section": "Item 1.05",\n            "target_context": "Full paragraph for context...",\n            "discrepancy_type": "omission",\n            "timeline_mismatch": {\n                "internal_date": "2024-10-27",\n                "disclosed_date": null,\n                "delay_days": null\n            }\n        }\n        '),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        AI processing metadata. Example:\n        {\n            "model": "claude-3-sonnet",\n            "model_version": "20240229-v1:0",\n            "confidence_score": 0.95,\n            "processing_time_ms": 3420,\n            "prompt_tokens": 4500,\n            "completion_tokens": 1200,\n            "total_cost_usd": 0.0576,\n            "analysis_timestamp": "2025-11-07T16:30:00Z",\n            "prompt_template_version": "v1.2"\n        }\n        '),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        Recommendations for remediation. Example:\n        {\n            "actions": [\n                {\n                    "priority": "immediate",\n                    "description": "Alert General Counsel",\n                    "timeline": "Next 2 hours",\n                    "responsible_party": "Compliance Officer"\n                },\n                {\n                    "priority": "high",\n                    "description": "File amended 8-K",\n                    "timeline": "Within 4 business days",\n                    "responsible_party": "Legal Department"\n                }\n            ],\n            "suggested_language": "On October 27, 2024, the Company experienced a cybersecurity incident...",\n            "financial_risk": {\n                "estimated_penalty_min": 1500000,\n                "estimated_penalty_max": 7000000,\n                "basis": "Recent SEC enforcement actions",\n                "precedents": [\n                    {"company": "Example Corp", "penalty": 3500000, "year": 2024}\n                ]\n            },\n            "regulatory_deadlines": {\n                "form_8k_deadline": "2024-10-31T23:59:59Z",\n                "days_remaining": 2\n            }\n        }\n        '),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Current status of the violation'),
    sa.Column('assigned_to_email', sa.String(length=255), nullable=True, comment='Email of person assigned to remediate'),
    sa.Column('assigned_to_name', sa.String(length=255), nullable=True, comment='Name of person assigned to remediate'),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When the violation was resolved'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='Notes about how the violation was resolved'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_violations_ai_metadata_gin', 'violations', ['ai_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_violations_assigned', 'violations', ['assigned_to_email', 'status'], unique=False)
    op.create_index('idx_violations_evidence_gin', 'violations', ['evidence'], unique=False, postgresql_using='gin')
    op.create_index('idx_violations_recommendations_gin', 'violations', ['recommendations'], unique=False, postgresql_using='gin')
    op.create_index('idx_violations_severity_status', 'violations', ['severity', 'status'], unique=False)
    op.create_index('idx_violations_type_framework', 'violations', ['violation_type', 'framework'], unique=False)
    op.create_index(op.f('ix_violations_assigned_to_email'), 'violations', ['assigned_to_email'], unique=False)
    op.create_index(op.f('ix_violations_created_at'), 'violations', ['created_at'], unique=False)
    op.create_index(op.f('ix_violations_framework'), 'violations', ['framework'], unique=False)
    op.create_index(op.f('ix_violations_id'), 'violations', ['id'], unique=False)
    op.create_index(op.f('ix_violations_severity'), 'violations', ['severity'], unique=False)
    op.create_index(op.f('ix_violations_source_document_id'), 'violations', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_violations_status'), 'violations', ['status'], unique=False)
    op.create_index(op.f('ix_violations_target_document_id'), 'violations', ['target_document_id'], unique=False)
    op.create_index(op.f('ix_violations_updated_at'), 'violations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_violations_violation_type'), 'violations', ['violation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_violation_type'), table_name='violations')
    op.drop_index(op.f('ix_violations_updated_at'), table_name='violations')
    op.drop_index(op.f('ix_violations_target_document_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_status'), table_name='violations')
    op.drop_index(op.f('ix_violations_source_document_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_severity'), table_name='violations')
    op.drop_index(op.f('ix_violations_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_framework'), table_name='violations')
    op.drop_index(op.f('ix_violations_created_at'), table_name='violations')
    op.drop_index(op.f('ix_violations_assigned_to_email'), table_name='violations')
    op.drop_index('idx_violations_type_framework', table_name='violations')
    op.drop_index('idx_violations_severity_status', table_name='violations')
    op.drop_index('idx_violations_recommendations_gin', table_name='violations', postgresql_using='gin')
    op.drop_index('idx_violations_evidence_gin', table_name='violations', postgresql_using='gin')
    op.drop_index('idx_violations_assigned', table_name='violations')
    op.drop_index('idx_violations_ai_metadata_gin', table_name='violations', postgresql_using='gin')
    op.drop_table('violations')
    op.drop_index(op.f('ix_scan_jobs_updated_at'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_triggered_by_email'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_framework'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_created_at'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_documents_uploaded_by_email'), table_name='documents')
    op.drop_index(op.f('ix_documents_updated_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_extraction_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index('idx_documents_uploaded_by', table_name='documents')
    op.drop_index('idx_documents_type_status', table_name='documents')
    op.drop_index('idx_documents_metadata_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_category_status', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
