"""fix_violation_foreign_keys_to_ingested_documents

Revision ID: 846fd5d64eeb
Revises: 002_compliance_frameworks
Create Date: 2025-11-10 20:30:00.222204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846fd5d64eeb'
down_revision: Union[str, Sequence[str], None] = '002_compliance_frameworks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compliance_frameworks', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Framework name (e.g., SOC 2 Type II)',
               existing_nullable=False)
    op.alter_column('compliance_frameworks', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Framework description',
               existing_nullable=True)
    op.alter_column('compliance_frameworks', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Framework version (e.g., 2023.1)',
               existing_nullable=True)
    op.alter_column('compliance_frameworks', 'framework_document_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to framework document in documents table',
               existing_nullable=True)
    op.alter_column('compliance_frameworks', 'framework_index_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Milvus collection name for framework documents',
               existing_nullable=False)
    op.alter_column('compliance_frameworks', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether framework is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('compliance_frameworks', 'created_by_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email of user who created the framework',
               existing_nullable=True)
    op.alter_column('compliance_frameworks', 'updated_by_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email of user who last updated the framework',
               existing_nullable=True)
    op.drop_constraint(op.f('compliance_frameworks_name_key'), 'compliance_frameworks', type_='unique')
    op.drop_index(op.f('idx_compliance_frameworks_framework_doc_id'), table_name='compliance_frameworks')
    op.drop_index(op.f('idx_compliance_frameworks_index_name'), table_name='compliance_frameworks')
    op.drop_index(op.f('idx_compliance_frameworks_is_active'), table_name='compliance_frameworks')
    op.drop_index(op.f('idx_compliance_frameworks_metadata_gin'), table_name='compliance_frameworks', postgresql_using='gin')
    op.drop_index(op.f('idx_compliance_frameworks_name'), table_name='compliance_frameworks')
    op.drop_index(op.f('idx_compliance_frameworks_todos_gin'), table_name='compliance_frameworks', postgresql_using='gin')
    op.create_index(op.f('ix_compliance_frameworks_created_at'), 'compliance_frameworks', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_frameworks_framework_document_id'), 'compliance_frameworks', ['framework_document_id'], unique=False)
    op.create_index(op.f('ix_compliance_frameworks_framework_index_name'), 'compliance_frameworks', ['framework_index_name'], unique=False)
    op.create_index(op.f('ix_compliance_frameworks_is_active'), 'compliance_frameworks', ['is_active'], unique=False)
    op.create_index(op.f('ix_compliance_frameworks_name'), 'compliance_frameworks', ['name'], unique=True)
    op.create_index(op.f('ix_compliance_frameworks_updated_at'), 'compliance_frameworks', ['updated_at'], unique=False)
    op.create_table_comment(
        'compliance_frameworks',
        'Compliance frameworks for regulatory standards',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'compliance_frameworks',
        existing_comment='Compliance frameworks for regulatory standards',
        schema=None
    )
    op.drop_index(op.f('ix_compliance_frameworks_updated_at'), table_name='compliance_frameworks')
    op.drop_index(op.f('ix_compliance_frameworks_name'), table_name='compliance_frameworks')
    op.drop_index(op.f('ix_compliance_frameworks_is_active'), table_name='compliance_frameworks')
    op.drop_index(op.f('ix_compliance_frameworks_framework_index_name'), table_name='compliance_frameworks')
    op.drop_index(op.f('ix_compliance_frameworks_framework_document_id'), table_name='compliance_frameworks')
    op.drop_index(op.f('ix_compliance_frameworks_created_at'), table_name='compliance_frameworks')
    op.create_index(op.f('idx_compliance_frameworks_todos_gin'), 'compliance_frameworks', ['compliance_todos'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_compliance_frameworks_name'), 'compliance_frameworks', ['name'], unique=True)
    op.create_index(op.f('idx_compliance_frameworks_metadata_gin'), 'compliance_frameworks', ['framework_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_compliance_frameworks_is_active'), 'compliance_frameworks', ['is_active'], unique=False)
    op.create_index(op.f('idx_compliance_frameworks_index_name'), 'compliance_frameworks', ['framework_index_name'], unique=False)
    op.create_index(op.f('idx_compliance_frameworks_framework_doc_id'), 'compliance_frameworks', ['framework_document_id'], unique=False)
    op.create_unique_constraint(op.f('compliance_frameworks_name_key'), 'compliance_frameworks', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('compliance_frameworks', 'updated_by_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email of user who last updated the framework',
               existing_nullable=True)
    op.alter_column('compliance_frameworks', 'created_by_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email of user who created the framework',
               existing_nullable=True)
    op.alter_column('compliance_frameworks', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether framework is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('compliance_frameworks', 'framework_index_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Milvus collection name for framework documents',
               existing_nullable=False)
    op.alter_column('compliance_frameworks', 'framework_document_id',
               existing_type=sa.UUID(),
               comment='Reference to framework document in documents table',
               existing_nullable=True)
    op.alter_column('compliance_frameworks', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='Framework version (e.g., 2023.1)',
               existing_nullable=True)
    op.alter_column('compliance_frameworks', 'description',
               existing_type=sa.TEXT(),
               comment='Framework description',
               existing_nullable=True)
    op.alter_column('compliance_frameworks', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Framework name (e.g., SOC 2 Type II)',
               existing_nullable=False)
    # ### end Alembic commands ###
