"""add_document_chunks_and_splits_tables

Revision ID: fb69163fd813
Revises: 6e191e0ff319
Create Date: 2025-11-07 20:47:02.833348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb69163fd813'
down_revision: Union[str, Sequence[str], None] = '6e191e0ff319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False, comment='Parent document ID'),
    sa.Column('chunk_id', sa.String(length=100), nullable=False, comment="Unique chunk ID from Landing AI (e.g., 'chunk-abc-123')"),
    sa.Column('chunk_type', sa.String(length=50), nullable=False, comment='Type of chunk: text, table, figure, form, etc.'),
    sa.Column('chunk_order', sa.Integer(), nullable=False, comment='Order of chunk in original document (0-indexed)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Markdown content of this chunk'),
    sa.Column('page_number', sa.Integer(), nullable=False, comment='Page number where this chunk appears (1-indexed)'),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        Bounding box coordinates in pixels:\n        {\n            "left": 100,\n            "top": 200,\n            "right": 500,\n            "bottom": 300\n        }\n        '),
    sa.Column('split_identifier', sa.String(length=100), nullable=True, comment='Identifier of the split/section this chunk belongs to'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.create_index('idx_chunks_bbox_gin', 'document_chunks', ['bounding_box'], unique=False, postgresql_using='gin')
    op.create_index('idx_chunks_document_page', 'document_chunks', ['document_id', 'page_number'], unique=False)
    op.create_index('idx_chunks_document_split', 'document_chunks', ['document_id', 'split_identifier'], unique=False)
    op.create_index('idx_chunks_document_type', 'document_chunks', ['document_id', 'chunk_type'], unique=False)
    op.create_index('idx_chunks_type_page', 'document_chunks', ['chunk_type', 'page_number'], unique=False)
    op.create_index(op.f('ix_document_chunks_chunk_type'), 'document_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_created_at'), 'document_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_document_chunks_page_number'), 'document_chunks', ['page_number'], unique=False)
    op.create_index(op.f('ix_document_chunks_split_identifier'), 'document_chunks', ['split_identifier'], unique=False)
    op.create_index(op.f('ix_document_chunks_updated_at'), 'document_chunks', ['updated_at'], unique=False)
    op.create_table('document_splits',
    sa.Column('document_id', sa.UUID(), nullable=False, comment='Parent document ID'),
    sa.Column('class', sa.String(length=50), nullable=False, comment='Class of split: section, chapter, etc.'),
    sa.Column('identifier', sa.String(length=100), nullable=False, comment='Section identifier: Item_1C, Risk_Factors, etc.'),
    sa.Column('pages', sa.ARRAY(sa.Integer()), nullable=False, comment='Array of page numbers covered by this split'),
    sa.Column('markdown', sa.Text(), nullable=True, comment='Combined markdown content of this section'),
    sa.Column('chunk_ids', sa.ARRAY(sa.String()), nullable=True, comment='Array of chunk IDs that belong to this split'),
    sa.Column('split_order', sa.Integer(), nullable=False, comment='Order of split in document (0-indexed)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_splits_chunks_gin', 'document_splits', ['chunk_ids'], unique=False, postgresql_using='gin')
    op.create_index('idx_splits_document_identifier', 'document_splits', ['document_id', 'identifier'], unique=False)
    op.create_index('idx_splits_identifier', 'document_splits', ['identifier'], unique=False)
    op.create_index('idx_splits_pages_gin', 'document_splits', ['pages'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_splits_created_at'), 'document_splits', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_splits_document_id'), 'document_splits', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_splits_id'), 'document_splits', ['id'], unique=False)
    op.create_index(op.f('ix_document_splits_identifier'), 'document_splits', ['identifier'], unique=False)
    op.create_index(op.f('ix_document_splits_updated_at'), 'document_splits', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_splits_updated_at'), table_name='document_splits')
    op.drop_index(op.f('ix_document_splits_identifier'), table_name='document_splits')
    op.drop_index(op.f('ix_document_splits_id'), table_name='document_splits')
    op.drop_index(op.f('ix_document_splits_document_id'), table_name='document_splits')
    op.drop_index(op.f('ix_document_splits_created_at'), table_name='document_splits')
    op.drop_index('idx_splits_pages_gin', table_name='document_splits', postgresql_using='gin')
    op.drop_index('idx_splits_identifier', table_name='document_splits')
    op.drop_index('idx_splits_document_identifier', table_name='document_splits')
    op.drop_index('idx_splits_chunks_gin', table_name='document_splits', postgresql_using='gin')
    op.drop_table('document_splits')
    op.drop_index(op.f('ix_document_chunks_updated_at'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_split_identifier'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_page_number'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_created_at'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_type'), table_name='document_chunks')
    op.drop_index('idx_chunks_type_page', table_name='document_chunks')
    op.drop_index('idx_chunks_document_type', table_name='document_chunks')
    op.drop_index('idx_chunks_document_split', table_name='document_chunks')
    op.drop_index('idx_chunks_document_page', table_name='document_chunks')
    op.drop_index('idx_chunks_bbox_gin', table_name='document_chunks', postgresql_using='gin')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
